import React,{useMemo,useState} from "react";
import {program} from "./data/program";
import {Home,Utensils,Dumbbell,ChartNoAxesColumnIncreasing,UserRound,Droplets,Footprints,Moon,Scale,Flame,Beef,ChevronRight,RefreshCw,HeartOff,Plus,X,Check,CalendarDays,Target,Settings2} from "lucide-react";
import "./styles.css";

type Store=Record<string,any>; type Meal=any;
const KEY="leanwell-v2";
const load=():Store=>{try{return JSON.parse(localStorage.getItem(KEY)||localStorage.getItem("leanwell-v1")||"{}")}catch{return {}}};
const todayISO=()=>{const d=new Date();const local=new Date(d.getTime()-d.getTimezoneOffset()*60000);return local.toISOString().slice(0,10)};
const clampDate=(x:string)=>x<program[0].date?program[0].date:x>program[program.length-1].date?program[program.length-1].date:x;
const mealPool=program.flatMap((d:any)=>d.meals).filter((m:any,i:number,a:any[])=>a.findIndex(x=>x.name===m.name)===i);
const forbiddenDefault=["eggs","egg","salmon","oats","oatmeal","cottage cheese","lentils","chickpeas","plain tuna"];
const compatible=(meal:Meal, current:Meal, dislikes:string[])=>meal.name!==current.name&&meal.label===current.label&&!dislikes.some(x=>(meal.name+" "+meal.ingredients).toLowerCase().includes(x.toLowerCase()))&&Math.abs(meal.calories-current.calories)<=180;

export default function App(){
 const [store,setStore]=useState<Store>(load()); const [tab,setTab]=useState("HOME"); const [date,setDate]=useState(clampDate(todayISO()));
 const day:any=program.find((d:any)=>d.date===date)||program[0];
 const patch=(p:Store)=>setStore(s=>{const n={...s,...p};localStorage.setItem(KEY,JSON.stringify(n));return n});
 if(!store.onboarded)return <Onboarding onDone={(profile:any)=>patch({onboarded:true,profile,dislikes:forbiddenDefault})}/>;
 return <div className="app-shell"><main className="screen">
  {tab==="HOME"&&<HomeScreen day={day} store={store} patch={patch} go={setTab}/>} {tab==="MEALS"&&<Meals day={day} store={store} patch={patch}/>} {tab==="WORKOUT"&&<Workout day={day} store={store} patch={patch}/>} {tab==="PROGRESS"&&<Progress store={store} date={date} setDate={setDate}/>} {tab==="PROFILE"&&<Profile store={store} patch={patch}/>} 
 </main><BottomNav tab={tab} setTab={setTab}/></div>
}
function BottomNav({tab,setTab}:any){const items:any[]=[["HOME",Home,"Today"],["MEALS",Utensils,"Meals"],["WORKOUT",Dumbbell,"Workout"],["PROGRESS",ChartNoAxesColumnIncreasing,"Progress"],["PROFILE",UserRound,"Profile"]];return <nav className="bottom-nav">{items.map(([id,Icon,label])=><button key={id} className={tab===id?"active":""} onClick={()=>setTab(id)}><Icon size={21}/><span>{label}</span></button>)}</nav>}
function Onboarding({onDone}:any){const [p,setP]=useState<any>({age:21,sex:"female",height:163,weight:78,goal:58,steps:7500,activity:"light",experience:"beginner",availability:5});const bmr=10*p.weight+6.25*p.height-5*p.age-(p.sex==="female"?161:-5);const factor:any={sedentary:1.25,light:1.4,moderate:1.55,high:1.7};const maintenance=Math.round(bmr*factor[p.activity]);const target=Math.max(p.sex==="female"?1400:1600,Math.round((maintenance-500)/50)*50);const protein=Math.round(Math.max(1.6*p.weight,1.8*Math.min(p.weight,p.goal)));return <div className="onboarding"><div className="brand-orb">L</div><p className="kicker">LEANWELL</p><h1>Your plan, made simple.</h1><p className="sub">Meals, workouts and progress in one calm place.</p><div className="surface form-card">{[["Weight (kg)","weight"],["Goal weight (kg)","goal"],["Height (cm)","height"],["Daily steps","steps"]].map(([l,k])=><label key={k}>{l}<input type="number" value={p[k]} onChange={e=>setP({...p,[k]:+e.target.value})}/></label>)}<button className="primary" onClick={()=>onDone({...p,maintenance,target,protein,carbs:Math.round((target-protein*4-55*9)/4),fat:55})}>Start LeanWell <ChevronRight size={18}/></button></div></div>}
function Header({eyebrow,title,action}:any){return <header className="top"><div><p className="kicker">{eyebrow}</p><h1>{title}</h1></div>{action}</header>}
function HomeScreen({day,store,patch,go}:any){const log=store.logs?.[day.date]||{};const profile=store.profile;const setLog=(p:any)=>patch({logs:{...(store.logs||{}),[day.date]:{...log,...p}}});const eaten=store.eaten?.[day.date]||[];const swaps=store.swaps?.[day.date]||{};const meals=day.meals.map((m:any,i:number)=>swaps[i]||m);const mealCals=meals.reduce((s:number,m:any)=>s+m.calories,0);const extra=eaten.reduce((s:number,m:any)=>s+(m.calories||0),0);const cal=log.calories||extra;return <><Header eyebrow={`DAY ${day.dayNumber} · WEEK ${day.week}`} title="Today" action={<div className="avatar">L</div>}/><section className="hero-new"><div><p>Daily target</p><h2>{profile.target}<small> kcal</small></h2><span>{Math.max(0,profile.target-cal)} kcal remaining</span></div><Ring value={Math.min(100,cal/profile.target*100)} label={`${cal}`} /></section><div className="stat-row"><Mini icon={<Beef/>} value={`${log.protein||0}g`} label={`of ${profile.protein}g protein`}/><Mini icon={<Footprints/>} value={`${log.steps||0}`} label={`of ${day.stepGoal} steps`}/><Mini icon={<Droplets/>} value={`${log.water||0}ml`} label="water"/></div><SectionHead title="Today's plan" action="View meals" onClick={()=>go("MEALS")}/><div className="surface plan-card"><div className="plan-icon"><Utensils/></div><div className="grow"><b>{meals.length} planned meals</b><span>{mealCals} kcal · high protein</span></div><ChevronRight/></div><div className="surface plan-card" onClick={()=>go("WORKOUT")}><div className="plan-icon"><Dumbbell/></div><div className="grow"><b>{day.workout.title}</b><span>{day.workout.type==="training"?"Strength + cardio":"Recovery day"}</span></div><ChevronRight/></div><SectionHead title="Quick log"/><div className="quick-grid"><Quick icon={<Scale/>} label="Weight" value={log.weight?`${log.weight} kg`:"Add"} onClick={()=>{const v=prompt("Morning weight (kg)",log.weight||"");if(v)setLog({weight:+v})}}/><Quick icon={<Footprints/>} label="Steps" value={log.steps||"Add"} onClick={()=>{const v=prompt("Steps",log.steps||"");if(v)setLog({steps:+v})}}/><Quick icon={<Droplets/>} label="Water" value="+250 ml" onClick={()=>setLog({water:(log.water||0)+250})}/><Quick icon={<Moon/>} label="Sleep" value={log.sleep?`${log.sleep} h`:"Add"} onClick={()=>{const v=prompt("Hours slept",log.sleep||"");if(v)setLog({sleep:+v})}}/></div></>}
function Ring({value,label}:any){return <div className="ring" style={{background:`conic-gradient(#536b58 ${value}%,#dce4dc 0)`}}><div><b>{label}</b><small>logged</small></div></div>}
function Mini({icon,value,label}:any){return <div className="mini">{React.cloneElement(icon,{size:17})}<b>{value}</b><span>{label}</span></div>}
function SectionHead({title,action,onClick}:any){return <div className="section-head"><h2>{title}</h2>{action&&<button onClick={onClick}>{action} <ChevronRight size={15}/></button>}</div>}
function Quick({icon,label,value,onClick}:any){return <button className="surface quick" onClick={onClick}><span className="quick-icon">{icon}</span><b>{value}</b><small>{label}</small></button>}
function Meals({day,store,patch}:any){const [sheet,setSheet]=useState<any>(null);const swaps=store.swaps?.[day.date]||{};const dislikes:string[]=store.dislikes||forbiddenDefault;const meals=day.meals.map((m:any,i:number)=>swaps[i]||m);const totals=meals.reduce((a:any,m:any)=>({calories:a.calories+m.calories,protein:a.protein+m.protein}),{calories:0,protein:0});const choose=(i:number,m:any)=>{patch({swaps:{...(store.swaps||{}),[day.date]:{...swaps,[i]:m}}});setSheet(null)};const dislike=(i:number,m:any)=>{const next=[...new Set([...dislikes,m.name])];const opts=mealPool.filter(x=>compatible(x,m,next));patch({dislikes:next,swaps:{...(store.swaps||{}),[day.date]:{...swaps,[i]:opts[0]||m}}});setSheet(null)};return <><Header eyebrow={day.date} title="Meals" action={<span className="target-chip">{totals.calories} kcal</span>}/><div className="macro-banner"><div><b>{totals.protein}g</b><span>Protein planned</span></div><div><b>{meals.length}</b><span>Meals today</span></div><div><b>{store.profile.target}</b><span>Calorie target</span></div></div>{meals.map((m:any,i:number)=><article className="surface meal-card" key={i}><div className="meal-top"><span className="meal-number">{i+1}</span><div className="grow"><p className="kicker">{m.label}</p><h3>{m.name}</h3></div><b>{m.calories}<small> kcal</small></b></div><p className="ingredients">{m.ingredients}</p><div className="macro-pills"><span>P {m.protein}g</span><span>C {m.carbs}g</span><span>F {m.fat}g</span></div><div className="meal-actions"><button onClick={()=>setSheet({i,m})}><RefreshCw size={16}/> Swap</button><button onClick={()=>dislike(i,m)}><HeartOff size={16}/> Don't like</button></div></article>)}<button className="add-food" onClick={()=>addOther(store,patch,day.date)}><Plus/> Log something else</button>{sheet&&<SwapSheet current={sheet.m} dislikes={dislikes} onClose={()=>setSheet(null)} onChoose={(m:any)=>choose(sheet.i,m)}/>}</>}
function SwapSheet({current,dislikes,onClose,onChoose}:any){const opts=mealPool.filter(m=>compatible(m,current,dislikes)).slice(0,5);return <div className="overlay" onClick={onClose}><div className="sheet" onClick={e=>e.stopPropagation()}><div className="sheet-handle"/><div className="sheet-title"><div><p className="kicker">SWAP MEAL</p><h2>Choose another</h2></div><button onClick={onClose}><X/></button></div><p className="sub">Similar calories and protein, without foods you've disliked.</p>{opts.length?opts.map((m:any)=><button className="swap-option" key={m.name} onClick={()=>onChoose(m)}><div><b>{m.name}</b><span>{m.calories} kcal · {m.protein}g protein</span></div><ChevronRight/></button>):<div className="empty">No close match yet. Use “Log something else” to add your own meal.</div>}</div></div>}
function addOther(store:any,patch:any,date:string){const food=prompt("What did you eat?");if(!food)return;const calories=+(prompt("Calories")||0);const protein=+(prompt("Protein (g)")||0);const old=store.eaten?.[date]||[];patch({eaten:{...(store.eaten||{}),[date]:[...old,{food,calories,protein}]}})}
function Workout({day,store,patch}:any){const state=store.workouts?.[day.date]||{};const update=(p:any)=>patch({workouts:{...(store.workouts||{}),[day.date]:{...state,...p}}});return <><Header eyebrow={day.date} title="Workout" action={state.completed?<span className="done-chip"><Check size={15}/> Done</span>:null}/><div className="workout-hero"><div className="plan-icon big"><Dumbbell/></div><p className="kicker">TODAY'S SESSION</p><h2>{day.workout.title}</h2><span>{day.workout.type==="training"?`${day.workout.exercises.length} exercises · ${day.workout.cardio}`:"Recovery + mobility"}</span></div>{day.workout.type==="training"&&<><WorkoutBlock title="Warm-up" items={day.workout.warmup}/><SectionHead title="Strength"/>{day.workout.exercises.map((e:any,i:number)=><div className="surface exercise-card" key={e.name}><span className="exercise-index">{i+1}</span><div className="grow"><h3>{e.name}</h3><p>{e.sets} sets × {e.reps} · Rest {e.rest}</p><span>{e.target} · RPE {e.rpe}</span><small>{e.form}</small></div></div>)}<WorkoutBlock title="Cardio" items={[day.workout.cardio]}/><WorkoutBlock title="Cool-down" items={day.workout.cooldown}/></>}{day.workout.type!=="training"&&<WorkoutBlock title="Recovery checklist" items={[`Reach ${day.stepGoal} steps`,day.workout.cardio,...day.workout.cooldown]}/>}<button className={state.completed?"primary completed":"primary"} onClick={()=>update({completed:!state.completed})}>{state.completed?<><Check/> Workout complete</>:<>Mark workout complete <Check/></>}</button></>}
function WorkoutBlock({title,items}:any){return <div className="surface workout-block"><h3>{title}</h3>{items.map((x:string)=><div className="check-line" key={x}><span><Check size={14}/></span>{x}</div>)}</div>}
function Progress({store,date,setDate}:any){const logs=store.logs||{};const weights=Object.entries(logs).filter(([_,v]:any)=>v.weight).map(([d,v]:any)=>({d,w:v.weight}));const current=weights.length?weights[weights.length-1].w:undefined;const start=weights[0]?.w;return <><Header eyebrow="YOUR JOURNEY" title="Progress"/><div className="progress-hero"><Target/><div><span>Goal weight</span><h2>{store.profile.goal} kg</h2></div><div><span>Current</span><h2>{current?`${current} kg`:"—"}</h2></div></div><div className="stat-row progress-stats"><Mini icon={<Scale/>} value={start?`${start} kg`:"—"} label="starting"/><Mini icon={<ChartNoAxesColumnIncreasing/>} value={start&&current?`${(current-start).toFixed(1)} kg`:"—"} label="change"/><Mini icon={<Flame/>} value={`${Object.values(store.workouts||{}).filter((x:any)=>x.completed).length}`} label="workouts"/></div><SectionHead title="Program calendar"/><div className="surface calendar-card"><div className="calendar">{program.map((d:any)=><button className={`day ${date===d.date?"selected":""} ${store.workouts?.[d.date]?.completed?"done":""}`} key={d.date} onClick={()=>setDate(d.date)}>{new Date(d.date+"T12:00").getDate()}</button>)}</div></div></>}
function Profile({store,patch}:any){const p=store.profile;const dislikes:string[]=store.dislikes||[];const [newFood,setNewFood]=useState("");return <><Header eyebrow="LEANWELL" title="Profile" action={<Settings2/>}/><div className="surface profile-card"><div className="avatar large">L</div><div><h2>Your plan</h2><span>Through November 20, 2026</span></div></div><SectionHead title="Daily targets"/><div className="surface settings-list"><Setting label="Calories" value={`${p.target} kcal`}/><Setting label="Protein" value={`${p.protein} g`}/><Setting label="Steps" value={`${p.steps||7500}`}/><Setting label="Goal weight" value={`${p.goal} kg`}/></div><SectionHead title="Food preferences"/><div className="surface preference-card"><p className="sub">LeanWell won't suggest foods on this list.</p><div className="tags">{dislikes.map((x:string)=><button key={x} onClick={()=>patch({dislikes:dislikes.filter(y=>y!==x)})}>{x}<X size={13}/></button>)}</div><div className="add-pref"><input value={newFood} onChange={e=>setNewFood(e.target.value)} placeholder="Add a food you don't like"/><button onClick={()=>{if(newFood.trim()){patch({dislikes:[...new Set([...dislikes,newFood.trim()])]});setNewFood("")}}}><Plus/></button></div></div></>}
function Setting({label,value}:any){return <div className="setting"><span>{label}</span><b>{value}</b></div>}
